import fs from 'node:fs/promises';
import path from 'node:path';
import type { Shortcut, Store } from './types.js';
import { ALIASES_OUTPUT, GENERATED_DIR, STATS_LOG_PATH } from '../lib/paths.js';

const HEADER = `#!/usr/bin/env bash
# ─────────────────────────────────────────────
#  Generated by halias — DO NOT EDIT MANUALLY
#  편집은 'halias add' / 'halias edit' 를 사용하세요.
# ─────────────────────────────────────────────

# 사용 통계 추적 함수
# 형식: <timestamp>\t<name>\t<directory>
# 탭 구분 — 미래에 필드 추가해도 안전, 디렉토리에 공백 있어도 OK
HALIAS_STATS_LOG="${STATS_LOG_PATH}"
_halias_track() {
  # 동기 쓰기 — 한 줄 append는 1ms 미만이라 사용자가 체감 못 함.
  # 백그라운드(&)로 처리하면 zsh가 [job] done 알림을 띄워서 UX가 망가짐.
  printf '%s\\t%s\\t%s\\n' "$(date +%s)" "$1" "$PWD" >> "$HALIAS_STATS_LOG" 2>/dev/null
}

# ─── Built-in 메타 명령 ────────────────────────
# halias 자체가 제공하는 셸 명령. 사용자 단축키와 충돌 방지를 위해 ha- prefix 사용.

# 새로 추가/편집한 단축키를 현재 셸에 즉시 반영
hareload() {
  source "${ALIASES_OUTPUT}"
  echo "✓ halias reloaded"
}

`;

/** 문자열을 셸 작은따옴표로 안전하게 감쌈 (내부의 ' 는 '\'' 로 이스케이프). */
function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * alias 명령에 인자 forwarding("$@")을 붙여도 안전한지 판정.
 *
 * 파이프/리다이렉트/논리연산/서브셸 등 메타문자가 있으면 "$@"가 엉뚱한 위치에
 * 붙어 의미가 바뀐다 (예: `ls -la | less` → `ls -la | less "$@"`).
 * 이런 경우엔 forwarding을 생략하고 명령을 그대로 실행한다.
 */
function canForwardArgs(command: string): boolean {
  return !/[|&;<>`(){}]|\$\(/.test(command);
}

/**
 * Shortcut 하나를 셸 함수 정의로 변환.
 *
 * 모든 단축키를 함수로 통일 생성 — wrapper 통계를 일관되게 적용 가능.
 * - alias 타입: command를 호출하고, 단순 명령이면 "$@" 전달
 * - function 타입: 사용자가 작성한 본문을 그대로 사용 ($1, $2 등 사용 가능)
 *
 * 함수 정의는 eval 로 감싼다. 사용자 본문에 문법 오류가 하나 있어도 그 단축키만
 * 조용히 건너뛰고, 파일 전체 source (나머지 단축키 + hareload)가 죽지 않게 격리.
 */
function renderShortcut(shortcut: Shortcut): string {
  const meta: string[] = [];

  if (shortcut.description) {
    // 개행은 주석 밖으로 코드가 새는 걸 막기 위해 공백으로 평탄화
    meta.push(`# ${shortcut.description.replace(/\r?\n/g, ' ')}`);
  }
  if (shortcut.tags.length > 0) {
    meta.push(`# tags: ${shortcut.tags.join(', ')}`);
  }
  meta.push(`# source: ${shortcut.source}`);

  const body: string[] = [];
  body.push(`${shortcut.name}() {`);
  body.push(`  _halias_track "${shortcut.name}"`);

  if (shortcut.type === 'alias') {
    body.push(canForwardArgs(shortcut.command) ? `  ${shortcut.command} "$@"` : `  ${shortcut.command}`);
  } else {
    // 함수 본문: 사용자 코드를 들여쓰기해서 삽입
    const indented = shortcut.command
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n');
    body.push(indented);
  }

  body.push('}');

  const definition = body.join('\n');
  const guarded =
    `eval ${shellSingleQuote(definition)} 2>/dev/null || ` +
    `printf 'halias: skipped broken shortcut %s\\n' ${shellSingleQuote(shortcut.name)} >&2`;

  return [...meta, guarded].join('\n');
}

export async function generateAliasesFile(store: Store): Promise<string> {
  await fs.mkdir(GENERATED_DIR, { recursive: true });

  const sections = store.shortcuts.map(renderShortcut).join('\n\n');
  const content = HEADER + sections + '\n';

  await fs.writeFile(ALIASES_OUTPUT, content, 'utf-8');
  return ALIASES_OUTPUT;
}
