import fs from 'node:fs/promises';
import path from 'node:path';
import type { Shortcut, Store } from './types.js';
import { ALIASES_OUTPUT, GENERATED_DIR, STATS_LOG_PATH } from '../lib/paths.js';

const HEADER = `#!/usr/bin/env bash
# ─────────────────────────────────────────────
#  Generated by halias — DO NOT EDIT MANUALLY
#  편집은 'halias add' / 'halias edit' 를 사용하세요.
# ─────────────────────────────────────────────

# 사용 통계 추적 함수
# 형식: <timestamp>\t<name>\t<directory>
# 탭 구분 — 미래에 필드 추가해도 안전, 디렉토리에 공백 있어도 OK
HALIAS_STATS_LOG="${STATS_LOG_PATH}"
_halias_track() {
  # 동기 쓰기 — 한 줄 append는 1ms 미만이라 사용자가 체감 못 함.
  # 백그라운드(&)로 처리하면 zsh가 [job] done 알림을 띄워서 UX가 망가짐.
  printf '%s\\t%s\\t%s\\n' "$(date +%s)" "$1" "$PWD" >> "$HALIAS_STATS_LOG" 2>/dev/null
}

# ─── Built-in 메타 명령 ────────────────────────
# halias 자체가 제공하는 셸 명령. 사용자 단축키와 충돌 방지를 위해 ha- prefix 사용.

# 새로 추가/편집한 단축키를 현재 셸에 즉시 반영
hareload() {
  source "${ALIASES_OUTPUT}"
  echo "✓ halias reloaded"
}

`;

/**
 * Shortcut 하나를 셸 함수 정의로 변환.
 *
 * 모든 단축키를 함수로 통일 생성 — wrapper 통계를 일관되게 적용 가능.
 * - alias 타입: command를 그대로 호출하고 "$@" 전달
 * - function 타입: 사용자가 작성한 본문을 그대로 사용 ($1, $2 등 사용 가능)
 */
function renderShortcut(shortcut: Shortcut): string {
  const lines: string[] = [];

  if (shortcut.description) {
    lines.push(`# ${shortcut.description}`);
  }
  if (shortcut.tags.length > 0) {
    lines.push(`# tags: ${shortcut.tags.join(', ')}`);
  }
  lines.push(`# source: ${shortcut.source}`);

  lines.push(`${shortcut.name}() {`);
  lines.push(`  _halias_track "${shortcut.name}"`);

  if (shortcut.type === 'alias') {
    // 단순 명령 + 추가 인자 forwarding
    lines.push(`  ${shortcut.command} "$@"`);
  } else {
    // 함수 본문: 사용자 코드를 들여쓰기해서 삽입
    const indented = shortcut.command
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n');
    lines.push(indented);
  }

  lines.push('}');
  return lines.join('\n');
}

export async function generateAliasesFile(store: Store): Promise<string> {
  await fs.mkdir(GENERATED_DIR, { recursive: true });

  const sections = store.shortcuts.map(renderShortcut).join('\n\n');
  const content = HEADER + sections + '\n';

  await fs.writeFile(ALIASES_OUTPUT, content, 'utf-8');
  return ALIASES_OUTPUT;
}
